all:
	bison -d -v  syntax.y
	flex lexical.l
	gcc  main.c semantic.c symboltable.c node.c -ll  -o parser



testall:
	./parser ./test/test_1.cmm
	./parser ./test/test_2.cmm
	./parser ./test/test_3.cmm
	./parser ./test/test_4.cmm
	./parser ./test/test_5.cmm
	./parser ./test/test_6.cmm
	./parser ./test/test_7.cmm
	./parser ./test/test_8.cmm
	./parser ./test/test_9.cmm
	./parser ./test/test_10.cmm
	./parser ./test/test_11.cmm
	./parser ./test/test_12.cmm
	./parser ./test/test_13.cmm
	./parser ./test/test_14.cmm
	./parser ./test/test_15.cmm
	./parser ./test/test_16.cmm
	./parser ./test/test_17.cmm
	./parser ./test/test_extra_1.cmm
	./parser ./test/test_extra_2.cmm
	./parser ./test/test_extra_3.cmm
	./parser ./test/test_extra_4.cmm
	./parser ./test/test_extra_5.cmm
	./parser ./test/test_extra_6.cmm
	



test1:
	./parser ./test/test_1.cmm

test2:
	./parser ./test/test_2.cmm

test3:
	./parser ./test/test_3.cmm

test4:
	./parser ./test/test_4.cmm

test5:
	./parser ./test/test_5.cmm

test6:
	./parser ./test/test_6.cmm

test7:
	./parser ./test/test_7.cmm

test8:
	./parser ./test/test_8.cmm

test9:
	./parser ./test/test_9.cmm

test10:
	./parser ./test/test_10.cmm

test11:
	./parser ./test/test_11.cmm

test12:
	./parser ./test/test_12.cmm

test13:
	./parser ./test/test_13.cmm

test14:
	./parser ./test/test_14.cmm

test15:
	./parser ./test/test_15.cmm

test16:
	./parser ./test/test_16.cmm

test17:
	./parser ./test/test_17.cmm

testex1:
	./parser ./test/test_extra_1.cmm

testex2:
	./parser ./test/test_extra_2.cmm

testex3:
	./parser ./test/test_extra_3.cmm

testex4:
	./parser ./test/test_extra_4.cmm

testex5:
	./parser ./test/test_extra_5.cmm

testex6:
	./parser ./test/test_extra_6.cmm

